production: &production
  url: <%= ENV.fetch("REDIS_URL", "redis://127.0.0.1:6379") %>
  ssl: true
  ssl_params: {
    verify_mode: OpenSSL::SSL::VERIFY_NONE 
  }
  timeout: 1

development: &development
  host: <%= ENV.fetch("REDIS_SHARED_HOST", "127.0.0.1") %>
  port: <%= ENV.fetch("REDIS_SHARED_PORT", "6379") %>
  timeout: 1

test:
  <<: *development
